
all: parent_child fork_exec

parent_child: parent_child.c
	gcc -Wall -Werror -Wpedantic -std=gnu2x -O2 parent_child.c -o parent_child
fork_exec: fork_exec.c
	gcc -Wall -Werror -Wpedantic -std=gnu2x -O2 fork_exec.c -o fork_exec