
all: parent_child run_prog

parent_child: parent_child.c
	gcc -Wall -Werror -Wpedantic -std=gnu2x -O2 parent_child.c -o parent_child
run_prog: run_prog.c
	gcc -Wall -Werror -Wpedantic -std=gnu2x -O2 run_prog.c -o run_prog